'use strict';
const $=id=>document.getElementById(id);
const ui={audio:$('audio'),video:$('video'),canvas:$('preview'),wrap:$('canvasWrap'),audioFile:$('audioFile'),visualFile:$('visualFile'),lyrics:$('lyrics'),phrases:$('phrases'),status:$('status')};
const ctx=ui.canvas.getContext('2d',{alpha:false});
const presets=['fade','pop','slide','glow','type','zoom','wave'];
const fonts=['bold','serif','rounded','mono'];
const state={phrases:[],duration:180,ratio:'9:16',visual:null,visualType:null,audioURL:null,visualURL:null,exporting:false,syncIndex:0,random:false,raf:0,audioContext:null,audioSource:null,output:null};
function setStatus(message){ui.status.textContent=message}
function format(t){t=Math.max(0,Number(t)||0);return `${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`}
function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function resize(){const landscape=$('ratio').value==='16:9';ui.canvas.width=landscape?960:540;ui.canvas.height=landscape?540:960;ui.canvas.style.aspectRatio=landscape?'16/9':'9/16';draw()}
function seeded(n){let x=Math.sin(n*91.345+13.67)*43758.5453;return x-Math.floor(x)}
function randomStyle(i){return {effect:presets[Math.floor(seeded(i+4)*presets.length)],font:fonts[Math.floor(seeded(i+21)*fonts.length)],color:['#ffffff','#fef08a','#ffadcf','#a5efff'][Math.floor(seeded(i+40)*4)]}}
function duration(){return Number.isFinite(ui.audio.duration)&&ui.audio.duration>0?ui.audio.duration:state.duration}
function parseLyrics(){const raw=ui.lyrics.value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean);if(!raw.length){setStatus('先に歌詞を入力してください。');return}
 const lrc=raw.map(line=>{const m=line.match(/^\[(\d{1,3}):(\d{2})(?:[.:](\d{1,3}))?\]\s*(.*)$/);return m?{start:Number(m[1])*60+Number(m[2])+Number('0.'+(m[3]||'0').padEnd(2,'0')),text:m[4]}:null});
 const hasLrc=lrc.every(Boolean);const lines=hasLrc?lrc.filter(x=>x.text):raw.map(text=>({text}));if(!lines.length)return;
 const total=duration();state.phrases=lines.map((item,i)=>({text:item.text,start:hasLrc?item.start:i*total/lines.length,effect:'fade',font:'global',color:''}));state.phrases.sort((a,b)=>a.start-b.start);state.syncIndex=0;renderPhrases();draw();$('parseNote').textContent=hasLrc?'LRCの時刻を読み込みました。':'フレーズを仮配置しました。「再生位置で記録」で曲に合わせてください。';}
function renderPhrases(){if(!state.phrases.length){ui.phrases.innerHTML='<p class="empty">歌詞を貼って「フレーズを作成」を押してください。</p>';return}
 ui.phrases.innerHTML=state.phrases.map((p,i)=>`<div class="phrase" data-index="${i}"><div class="phrase-head"><b>${String(i+1).padStart(2,'0')}</b><input data-field="text" aria-label="${i+1}番の歌詞" value="${escapeHTML(p.text)}"></div><div class="phrase-controls"><label>開始（秒）<input data-field="start" type="number" min="0" max="${Math.ceil(duration())}" step="0.01" value="${p.start.toFixed(2)}"></label><label>演出<select data-field="effect">${['fade','pop','slide','glow','type','zoom','wave'].map(v=>`<option value="${v}" ${p.effect===v?'selected':''}>${{fade:'フェード',pop:'ポップ',slide:'スライド',glow:'発光',type:'タイプ',zoom:'ズーム',wave:'ゆらぎ'}[v]}</option>`).join('')}</select></label><label>フォント<select data-field="font">${['global','bold','serif','rounded','mono'].map(v=>`<option value="${v}" ${p.font===v?'selected':''}>${{global:'全体設定',bold:'太ゴシック',serif:'明朝',rounded:'丸ゴシック',mono:'モノ'}[v]}</option>`).join('')}</select></label><label>文字色<input data-field="color" type="color" value="${p.color||$('globalColor').value}"></label></div><div class="phrase-actions"><button data-action="jump">ここから再生</button><button data-action="set">現在位置に設定</button><button data-action="delete">削除</button></div></div>`).join('');highlight()}
ui.phrases.addEventListener('input',e=>{const field=e.target.dataset.field;if(!field)return;const row=e.target.closest('.phrase'),p=state.phrases[Number(row.dataset.index)];if(field==='start'){if(e.target.value==='')return;p.start=Math.max(0,Math.min(duration(),Number(e.target.value)||0))}else p[field]=e.target.value;draw()});
ui.phrases.addEventListener('click',e=>{const action=e.target.dataset.action;if(!action)return;const i=Number(e.target.closest('.phrase').dataset.index);if(action==='delete'){state.phrases.splice(i,1);state.syncIndex=Math.min(state.syncIndex,state.phrases.length);renderPhrases();draw()}if(action==='set'){state.phrases[i].start=ui.audio.currentTime;renderPhrases();draw()}if(action==='jump'){ui.audio.currentTime=state.phrases[i].start;syncVideo();draw();ui.audio.play().catch(()=>setStatus('先に音楽を選択してください。'))}});
function currentPhrase(t){let idx=-1;for(let i=0;i<state.phrases.length;i++)if(t>=state.phrases[i].start&&(!state.phrases[i+1]||t<state.phrases[i+1].start))idx=i;return idx}
function highlight(){const active=currentPhrase(ui.audio.currentTime);ui.phrases.querySelectorAll('.phrase').forEach((el,i)=>el.classList.toggle('active',i===active))}
function cover(media,w,h){const sw=media.videoWidth||media.naturalWidth,sh=media.videoHeight||media.naturalHeight;if(!sw||!sh)return false;const scale=Math.max(w/sw,h/sh);const dw=sw*scale,dh=sh*scale;ctx.drawImage(media,(w-dw)/2,(h-dh)/2,dw,dh);return true}
function background(t,w,h){const grad=ctx.createLinearGradient(0,0,w,h);grad.addColorStop(0,'#522e78');grad.addColorStop(.52,'#1b3564');grad.addColorStop(1,'#c75082');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);if(state.visual){try{cover(state.visual,w,h)}catch{}}else{ctx.fillStyle='#ffffff12';for(let i=0;i<15;i++){const x=(seeded(i+30)*w+Math.sin(t*.3+i)*18)%w,y=(seeded(i+90)*h+t*(i%4+1)*3)%h,r=(seeded(i+4)*45+10)*w/540;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}}
 ctx.fillStyle=`rgba(0,0,0,${Number($('dim').value)/100})`;ctx.fillRect(0,0,w,h)}
function wrapText(text,maxWidth){const result=[];for(const rawLine of text.split('\n')){let line='';for(const char of Array.from(rawLine)){if(line&&ctx.measureText(line+char).width>maxWidth){result.push(line);line=char}else line+=char}result.push(line)}return result}
function fontCSS(font,size){return `${font==='serif'?'700':font==='mono'?'700':'800'} ${size}px ${font==='serif'?`"Hiragino Mincho ProN","Yu Mincho",serif`:font==='mono'?`ui-monospace,monospace`:font==='rounded'?`"Hiragino Maru Gothic ProN",system-ui,sans-serif`:`"Hiragino Kaku Gothic ProN",system-ui,sans-serif`}`}
function draw(time=ui.audio.currentTime){const w=ui.canvas.width,h=ui.canvas.height,t=Number.isFinite(time)?time:0;background(t,w,h);const idx=currentPhrase(t);if(idx<0)return;const p=state.phrases[idx],next=state.phrases[idx+1];const elapsed=t-p.start,life=Math.max(.2,(next?next.start:duration())-p.start),fadeOut=Math.min(1,Math.max(0,(life-elapsed)/.23));let alpha=Math.min(1,Math.max(0,elapsed/.27))*fadeOut,scale=1,offsetY=0;
 if(p.effect==='pop'){scale=1+Math.max(0,1-elapsed/.42)*.26;alpha=fadeOut}else if(p.effect==='slide'){offsetY=Math.max(0,1-elapsed/.4)*h*.09}else if(p.effect==='zoom'){scale=1.13-Math.min(1,elapsed/life)*.13}else if(p.effect==='wave'){offsetY=Math.sin(elapsed*6)*h*.008}else if(p.effect==='glow'){alpha=fadeOut}
 const gfont=$('globalFont').value;const font=p.font==='global'?(gfont==='random'?fonts[Math.floor(seeded(idx+21)*fonts.length)]:gfont):p.font;let size=Number($('fontSize').value)*w/540;ctx.font=fontCSS(font,size);const maxWidth=w*.83;let lines=wrapText(p.text,maxWidth);if(lines.length>4){size*=4/lines.length;ctx.font=fontCSS(font,size);lines=wrapText(p.text,maxWidth)}const lineHeight=size*1.3,totalHeight=lines.length*lineHeight;
 ctx.save();ctx.globalAlpha=alpha;ctx.translate(w/2,h*.52+offsetY);ctx.scale(scale,scale);ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineJoin='round';ctx.strokeStyle='#080717c7';ctx.lineWidth=Math.max(5,size*.13);ctx.fillStyle=p.color||$('globalColor').value;
 if(p.effect==='glow'){ctx.shadowBlur=size*.6;ctx.shadowColor=ctx.fillStyle}
 lines.forEach((line,i)=>{let visible=line;if(p.effect==='type'){const count=Math.max(0,Math.ceil((elapsed/.85)*Array.from(p.text).length));visible=Array.from(line).slice(0,Math.max(0,count-lines.slice(0,i).reduce((a,v)=>a+Array.from(v).length,0))).join('')}const y=(i+.5)*lineHeight-totalHeight/2;ctx.strokeText(visible,0,y);ctx.fillText(visible,0,y)});ctx.restore()}
function frame(){draw();ui.raf=requestAnimationFrame(frame)}
function startFrame(){if(!ui.raf)ui.raf=requestAnimationFrame(frame)}
function stopFrame(){cancelAnimationFrame(ui.raf);ui.raf=0;draw()}
function tick(){const d=duration();$('seek').value=String(Math.min(1000,Math.round(ui.audio.currentTime/d*1000)));$('timeLabel').textContent=`${format(ui.audio.currentTime)} / ${format(d)}`;highlight()}
function syncVideo(){if(state.visualType!=='video')return;const v=ui.video;if(v.readyState<1)return;const target=ui.audio.currentTime%(v.duration||duration());if(Math.abs(v.currentTime-target)>.3)try{v.currentTime=target}catch{}if(ui.audio.paused)v.pause();else v.play().catch(()=>{})}
ui.audio.addEventListener('loadedmetadata',()=>{state.duration=duration();$('durationLabel').textContent=format(duration());tick();if(state.phrases.length&&$('parseNote').textContent.includes('仮配置'))equalTiming()});ui.audio.addEventListener('timeupdate',()=>{tick();if(state.visualType==='video'&&Math.abs(ui.video.currentTime-ui.audio.currentTime%(ui.video.duration||duration()))>.35)syncVideo()});ui.audio.addEventListener('play',()=>{$('playBtn').textContent='Ⅱ';syncVideo();startFrame()});ui.audio.addEventListener('pause',()=>{$('playBtn').textContent='▶';syncVideo();stopFrame()});ui.audio.addEventListener('ended',()=>{$('playBtn').textContent='▶';stopFrame()});
$('playBtn').onclick=async()=>{if(!state.audioURL){setStatus('先に音楽を選択してください。');return}try{if(ui.audio.paused){await setupAudio();await ui.audio.play()}else ui.audio.pause()}catch(err){setStatus(`再生できません: ${err.message}`)}};
$('seek').oninput=e=>{ui.audio.currentTime=Number(e.target.value)/1000*duration();syncVideo();tick();draw()};
ui.audioFile.onchange=e=>{const file=e.target.files[0];if(!file)return;if(state.audioURL)URL.revokeObjectURL(state.audioURL);state.audioURL=URL.createObjectURL(file);ui.audio.src=state.audioURL;$('audioName').textContent=file.name;setStatus('音楽を読み込みました。')};
ui.visualFile.onchange=e=>{const file=e.target.files[0];if(!file)return;if(state.visualURL)URL.revokeObjectURL(state.visualURL);state.visualURL=URL.createObjectURL(file);$('visualName').textContent=file.name;if(file.type.startsWith('video/')){state.visualType='video';ui.video.src=state.visualURL;state.visual=ui.video;ui.video.load()}else if(file.type.startsWith('image/')){state.visualType='image';const img=new Image();img.onload=draw;img.src=state.visualURL;state.visual=img}else{setStatus('動画または画像を選択してください。');return}draw()};
$('parseBtn').onclick=parseLyrics;
function equalTiming(){const d=duration();state.phrases.forEach((p,i)=>p.start=i*d/state.phrases.length);state.syncIndex=0;renderPhrases();draw()}
$('resetTimingBtn').onclick=equalTiming;
$('syncBtn').onclick=()=>{if(!state.phrases.length)return setStatus('先にフレーズを作成してください。');if(!state.audioURL)return setStatus('先に音楽を選択してください。');if(state.syncIndex>=state.phrases.length){state.syncIndex=0;setStatus('最初のフレーズに戻りました。もう一度押して記録できます。');return}state.phrases[state.syncIndex].start=ui.audio.currentTime;state.syncIndex++;renderPhrases();setStatus(`${state.syncIndex} / ${state.phrases.length} フレーズを記録しました。`)};
$('autoBtn').onclick=()=>{if(!state.phrases.length)parseLyrics();state.phrases.forEach((p,i)=>Object.assign(p,randomStyle(i)));$('globalFont').value='random';renderPhrases();draw();setStatus('フレーズごとに演出・フォント・色を割り当てました。')};
$('ratio').onchange=resize;for(const id of ['globalFont','globalColor','fontSize','dim'])$(id).addEventListener('input',draw);
async function setupAudio(){if(!state.audioContext){const C=window.AudioContext||window.webkitAudioContext;if(!C)throw new Error('このブラウザでは音声ミキシングを利用できません。');state.audioContext=new C();state.audioSource=state.audioContext.createMediaElementSource(ui.audio);state.output=state.audioContext.createMediaStreamDestination();state.audioSource.connect(state.output);state.audioSource.connect(state.audioContext.destination)}await state.audioContext.resume()}
function getMime(){if(!window.MediaRecorder)return '';const types=['video/mp4;codecs=avc1.42E01E,mp4a.40.2','video/mp4','video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'];return types.find(x=>MediaRecorder.isTypeSupported(x))||''}
async function exportVideo(){if(state.exporting)return;if(!state.audioURL)return setStatus('先に音楽を選択してください。');if(!state.phrases.length)return setStatus('先に歌詞のフレーズを作成してください。');if(!ui.canvas.captureStream||!window.MediaRecorder)return setStatus('このブラウザは動画書き出しに対応していません。PCのChromeまたは対応ブラウザで開いてください。');
 const mime=getMime();if(!mime)return setStatus('この端末は動画の録画形式に対応していません。PCのChromeでも試してください。');
 let recorder,stream,resolveStop;const final=new Promise(resolve=>resolveStop=resolve);const originalSize=[ui.canvas.width,ui.canvas.height];const button=$('exportBtn');let chunks=[];
 try{state.exporting=true;button.disabled=true;ui.audio.pause();ui.audio.currentTime=0;resize();const landscape=$('ratio').value==='16:9';ui.canvas.width=landscape?1920:1080;ui.canvas.height=landscape?1080:1920;draw(0);await setupAudio();stream=ui.canvas.captureStream(30);state.output.stream.getAudioTracks().forEach(track=>stream.addTrack(track));recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:8000000,audioBitsPerSecond:192000});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onerror=e=>{setStatus('書き出し中にエラーが発生しました。');resolveStop()};recorder.onstop=()=>resolveStop();
 recorder.start(1000);setStatus(`書き出し中：0%（曲の長さだけかかります）`);await ui.audio.play();startFrame();await new Promise((resolve,reject)=>{const onEnd=()=>{cleanup();resolve()};const onErr=()=>{cleanup();reject(new Error('音楽を再生できません。'))};function cleanup(){ui.audio.removeEventListener('ended',onEnd);ui.audio.removeEventListener('error',onErr)}ui.audio.addEventListener('ended',onEnd);ui.audio.addEventListener('error',onErr);if(ui.audio.ended)onEnd()});if(recorder.state!=='inactive')recorder.stop();await final;
 if(!chunks.length)throw new Error('録画データがありません。この端末のブラウザが動画録画をサポートしていない可能性があります。');const ext=mime.includes('mp4')?'mp4':'webm',blob=new Blob(chunks,{type:mime}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`lyric-stage-${Date.now()}.${ext}`;link.textContent=`動画を保存（${(blob.size/1048576).toFixed(1)} MB・${ext.toUpperCase()}）`;link.className='download';link.style.cssText='display:block;text-align:center;color:#fff;background:#7043ac;padding:12px;border-radius:9px';ui.status.replaceChildren(document.createTextNode('完成しました。保存が始まらない場合はこちら：'),link);link.click();setTimeout(()=>URL.revokeObjectURL(url),3600000);
 }catch(e){if(recorder&&recorder.state!=='inactive')recorder.stop();setStatus(`書き出し失敗：${e.message}`)}finally{state.exporting=false;button.disabled=false;ui.audio.pause();stream?.getVideoTracks().forEach(track=>track.stop());ui.canvas.width=originalSize[0];ui.canvas.height=originalSize[1];draw()}}
$('exportBtn').onclick=exportVideo;
ui.audio.addEventListener('timeupdate',()=>{if(state.exporting)ui.status.textContent=`書き出し中：${Math.floor(ui.audio.currentTime/duration()*100)}%（画面を閉じないでください）`});
$('saveBtn').onclick=()=>{const data={version:1,lyrics:ui.lyrics.value,phrases:state.phrases,ratio:$('ratio').value,font:$('globalFont').value,color:$('globalColor').value,fontSize:$('fontSize').value,dim:$('dim').value,duration:duration()};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='lyric-stage-project.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);setStatus('編集データを保存しました。音楽・映像ファイルは含まれないため、再開時に選び直してください。')};
$('loadBtn').onclick=()=>$('loadFile').click();$('loadFile').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(data.version!==1||!Array.isArray(data.phrases))throw new Error('対応していないデータです。');ui.lyrics.value=data.lyrics||'';state.phrases=data.phrases.filter(x=>typeof x.text==='string'&&Number.isFinite(x.start)).map(x=>({text:x.text,start:x.start,effect:presets.includes(x.effect)?x.effect:'fade',font:['global',...fonts].includes(x.font)?x.font:'global',color:/^#[0-9a-f]{6}$/i.test(x.color)?x.color:''}));state.duration=Number(data.duration)||180;$('ratio').value=data.ratio==='16:9'?'16:9':'9:16';$('globalFont').value=[...fonts,'random'].includes(data.font)?data.font:'bold';if(/^#[0-9a-f]{6}$/i.test(data.color))$('globalColor').value=data.color;$('fontSize').value=data.fontSize||68;$('dim').value=data.dim??30;resize();renderPhrases();setStatus('編集データを読み込みました。音楽・映像ファイルを選び直してください。')}catch(err){setStatus(`読み込み失敗：${err.message}`)}e.target.value=''};
$('networkState').textContent=navigator.onLine?'● オフライン対応':'● オフライン';window.addEventListener('online',()=>{$('networkState').textContent='● オフライン対応'});window.addEventListener('offline',()=>{$('networkState').textContent='● オフライン'});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));resize();tick();
